const esc = (value) => String(value).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c]);

export function reliabilitySvg(report, { title = 'groundproof reliability diagram' } = {}) {
  const width = 720, height = 560, left = 80, top = 70, size = 400;
  const points = report.table.filter((bin) => bin.count).map((bin) => `${left + bin.meanPredicted * size},${top + (1 - bin.empiricalGroundedRate) * size}`).join(' ');
  const circles = report.table.filter((bin) => bin.count).map((bin) => `<circle cx="${left + bin.meanPredicted * size}" cy="${top + (1 - bin.empiricalGroundedRate) * size}" r="${Math.min(14, 4 + Math.sqrt(bin.count) * 2)}" class="point"><title>n=${bin.count}; predicted=${bin.meanPredicted}; observed=${bin.empiricalGroundedRate}${bin.lowConfidence ? '; low-confidence bin' : ''}</title></circle>`).join('');
  const ticks = Array.from({ length: 6 }, (_, i) => i / 5).map((v) => `<text x="${left + v * size}" y="${top + size + 24}" text-anchor="middle">${v.toFixed(1)}</text><text x="${left - 14}" y="${top + (1 - v) * size + 4}" text-anchor="end">${v.toFixed(1)}</text>`).join('');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc"><title id="title">${esc(title)}</title><desc id="desc">Reliability diagram for ${report.n} items. ECE ${report.ece}, MCE ${report.mce}, Brier ${report.brier}. Small-sample estimate.</desc><style>text{font:14px system-ui,sans-serif;fill:#172033}.title{font-size:22px;font-weight:700}.axis{stroke:#172033}.perfect{stroke:#8a94a6;stroke-dasharray:7 6}.line{fill:none;stroke:#1769aa;stroke-width:3}.point{fill:#28a0b8;stroke:#07546a;stroke-width:2}</style><rect width="100%" height="100%" fill="#fff"/><text x="${left}" y="38" class="title">${esc(title)}</text><line x1="${left}" y1="${top + size}" x2="${left + size}" y2="${top}" class="perfect"/><line x1="${left}" y1="${top + size}" x2="${left + size}" y2="${top + size}" class="axis"/><line x1="${left}" y1="${top}" x2="${left}" y2="${top + size}" class="axis"/>${ticks}<polyline points="${points}" class="line"/>${circles}<text x="${left + size / 2}" y="${top + size + 55}" text-anchor="middle">Mean predicted confidence</text><text x="20" y="${top + size / 2}" transform="rotate(-90 20 ${top + size / 2})" text-anchor="middle">Empirical grounded rate</text><text x="510" y="100">n = ${report.n}</text><text x="510" y="125">ECE = ${report.ece}</text><text x="510" y="150">MCE = ${report.mce}</text><text x="510" y="175">Brier = ${report.brier}</text><text x="80" y="545" font-size="12">Small-sample ECE is noisy; use a full dev set for a meaningful figure.</text></svg>`;
}
